### ISSUE TITLE
running package in parallel natively reduces performance

### ISSUE THREAD

**Issue by adamhsparks** [IhsanKhaliq/ascotraceR#123]
I ran [this script](https://gist.github.com/adamhsparks/9f8ed676c6c18a014863459228aa31c7)  and got three very different timings for the same operation.

* the first, using `plan(multisession)` with `trace_asco()` resulted in 20 runs taking 132.281 sec.
* the second, using `plan(sequential)` with `trace_asco()` resulted in 20 runs taking 95.633 sec.
* the third, using `foreach` in place of the `for` loop with `trace_asco()` resulted in 20 runs taking only  27.466 sec.

The two parallel operations both used only 4 cores (when I used all 8 for the `foreach` it saved me ~2 sec.)

I suggest that the internal workings need to be examined for efficiency and fixed to improve this and/or parallelism in the package should be removed and examples showing the use of _future_lapply_/_furrr_/_foreach_ should be created.

My session info:

─ Session info  🇱🇻  🕟  👨‍🔬   ──────────────────────────────────────────────────────────────────────────────────────────────────
 hash: flag: Latvia, four-thirty, man scientist

 setting  value
 version  R version 4.1.2 (2021-11-01)
 os       macOS Big Sur 11.6.1
 system   aarch64, darwin20
 ui       RStudio
 language (EN)
 collate  en_AU.UTF-8
 ctype    en_AU.UTF-8
 tz       Australia/Perth
 date     2021-11-15
 rstudio  2021.09.0+351 Ghost Orchid (desktop)
 pandoc   2.14.0.3 @ /Applications/RStudio.app/Contents/MacOS/pandoc/ (via rmarkdown)

─ Packages ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
 package      * version    date (UTC) lib source
 ascotraceR   * 0.0.0.9000 2021-11-15 [1] local
 assertthat     0.2.1      2019-03-21 [1] CRAN (R 4.1.0)
 boot           1.3-28     2021-05-03 [1] CRAN (R 4.1.2)
 cellranger     1.1.0      2016-07-27 [1] CRAN (R 4.1.0)
 circular       0.4-93     2017-06-29 [1] CRAN (R 4.1.0)
 cli            3.1.0      2021-10-27 [1] CRAN (R 4.1.1)
 clipr          0.7.1      2020-10-08 [1] CRAN (R 4.1.0)
 codetools      0.2-18     2020-11-04 [1] CRAN (R 4.1.2)
 colorspace     2.0-2      2021-06-24 [1] CRAN (R 4.1.0)
 crayon         1.4.2      2021-10-29 [1] CRAN (R 4.1.1)
 data.table   * 1.14.2     2021-09-27 [1] CRAN (R 4.1.1)
 DBI            1.1.1      2021-01-15 [1] CRAN (R 4.1.0)
 digest         0.6.28     2021-09-23 [1] CRAN (R 4.1.1)
 doParallel     1.0.16     2020-10-16 [1] CRAN (R 4.1.0)
 dplyr        * 1.0.7      2021-06-18 [1] CRAN (R 4.1.0)
 ellipsis       0.3.2      2021-04-29 [1] CRAN (R 4.1.0)
 evaluate       0.14       2019-05-28 [1] CRAN (R 4.1.0)
 fansi          0.5.0      2021-05-25 [1] CRAN (R 4.1.0)
 fastmap        1.1.0      2021-01-25 [1] CRAN (R 4.1.0)
 foreach      * 1.5.1      2020-10-15 [1] CRAN (R 4.1.0)
 furrr        * 0.2.3      2021-06-25 [1] CRAN (R 4.1.0)
 future       * 1.23.0     2021-10-31 [1] CRAN (R 4.1.1)
 future.apply   1.8.1      2021-08-10 [1] CRAN (R 4.1.1)
 generics       0.1.1      2021-10-25 [1] CRAN (R 4.1.1)
 ggplot2      * 3.3.5      2021-06-25 [1] CRAN (R 4.1.0)
 globals        0.14.0     2020-11-22 [1] CRAN (R 4.1.0)
 glue           1.5.0      2021-11-07 [1] CRAN (R 4.1.2)
 gtable         0.3.0      2019-03-25 [1] CRAN (R 4.1.0)
 htmltools      0.5.2      2021-08-25 [1] CRAN (R 4.1.1)
 iterators      1.0.13     2020-10-15 [1] CRAN (R 4.1.0)
 knitr          1.36       2021-09-29 [1] CRAN (R 4.1.1)
 lifecycle      1.0.1      2021-09-24 [1] CRAN (R 4.1.1)
 listenv        0.8.0      2019-12-05 [1] CRAN (R 4.1.0)
 lubridate    * 1.8.0      2021-10-07 [1] CRAN (R 4.1.1)
 magrittr       2.0.1      2020-11-17 [1] CRAN (R 4.1.0)
 munsell        0.5.0      2018-06-12 [1] CRAN (R 4.1.0)
 mvtnorm        1.1-3      2021-10-08 [1] CRAN (R 4.1.1)
 parallelly     1.28.1     2021-09-09 [1] CRAN (R 4.1.1)
 patchwork    * 1.1.1      2020-12-17 [1] CRAN (R 4.1.1)
 pillar         1.6.4      2021-10-18 [1] CRAN (R 4.1.1)
 pkgconfig      2.0.3      2019-09-22 [1] CRAN (R 4.1.0)
 purrr          0.3.4      2020-04-17 [1] CRAN (R 4.1.0)
 R6             2.5.1      2021-08-19 [1] CRAN (R 4.1.1)
 Rcpp           1.0.7      2021-07-07 [1] CRAN (R 4.1.1)
 readxl       * 1.3.1      2019-03-13 [1] CRAN (R 4.1.0)
 rlang          0.4.12     2021-10-18 [1] CRAN (R 4.1.1)
 rmarkdown      2.11       2021-09-14 [1] CRAN (R 4.1.1)
 rstudioapi     0.13       2020-11-12 [1] CRAN (R 4.1.0)
 scales         1.1.1      2020-05-11 [1] CRAN (R 4.1.0)
 sessioninfo  * 1.2.1      2021-11-02 [1] CRAN (R 4.1.1)
 tibble         3.1.6      2021-11-07 [1] CRAN (R 4.1.2)
 tictoc       * 1.0.1      2021-04-19 [1] CRAN (R 4.1.0)
 tidyselect     1.1.1      2021-04-30 [1] CRAN (R 4.1.0)
 utf8           1.2.2      2021-07-24 [1] CRAN (R 4.1.0)
 vctrs          0.3.8      2021-04-29 [1] CRAN (R 4.1.0)
 withr          2.4.2      2021-04-18 [1] CRAN (R 4.1.0)
 xfun           0.28       2021-11-04 [1] CRAN (R 4.1.2)
 yaml           2.2.1      2020-02-01 [1] CRAN (R 4.1.0)

 [1] /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

**Comment by PaulMelloy** [comment]
Future functionality removed, before closing the following needs to be completed

- [ ] Check vignette to remove examples of using the internal future functionality

**Comment by adamhsparks** [comment]
There was no example using parallel processing in the current vignette that I found.
