### ISSUE TITLE
Release ascotraceR 0.0.1

### ISSUE THREAD

**Issue by adamhsparks** [IhsanKhaliq/ascotraceR#125]
First release:

* [x] `usethis::use_cran_comments()`
* [x] Update (aspirational) install instructions in README
* [x] Proofread `Title:` and `Description:`
* [x] Check that all exported functions have `@return` and `@examples`
* [x] Check that `Authors@R:` includes a copyright holder (role 'cph')
* [x] Check [licensing of included files](https://r-pkgs.org/license.html#code-you-bundle)
* [x] Review <https://github.com/DavisVaughan/extrachecks>

Prepare for release:

* [x] `devtools::build_readme()`
* [x] `urlchecker::url_check()`
* [x] `devtools::check(remote = TRUE, manual = TRUE)`
* [x] `devtools::check_win_devel()`
* [x] `rhub::check_for_cran()`
* [x] Update codemeta.json with `codemetar::write_codemeta()`

Submit to CRAN:

* [x] `usethis::use_version('patch')`
* [x] `devtools::release()`
* [x] Approve email

Wait for CRAN...

* [x] Accepted :tada:
* [x] `usethis::use_github_release()`
* [x] `usethis::use_dev_version()`
* [x] `usethis::use_news_md()`

**Comment by IhsanKhaliq** [comment]
Since this is close to submission, please see the open issue on `valascotraceR` before submission

**Comment by PaulMelloy** [comment]
All tasks complete
The package is now on CRAN
