### ISSUE TITLE
DESCRIPTION should reference Art and Moin's model

### ISSUE THREAD

**Issue by adamhsparks** [IhsanKhaliq/ascotraceR#126]
Head this one off at the pass:

> If there are references describing the methods in your package, please add these in the description field of your DESCRIPTION file in the form authors (year) <doi:…> authors (year) <arXiv:…> authors (year, ISBN:…) or if those are not available: <https:…> with no space after ‘doi:’, ‘arXiv:’, ‘https:’ and angle brackets for auto-linking. (If you want to add a title as well please put it in quotes: “Title”)

Include a reference to the original model paper in the DESCRIPTION's Description field.

**Comment by IhsanKhaliq** [comment]
Moin's paper has not been published. It's a Coventry's thesis chapter

**Comment by IhsanKhaliq** [comment]
Closed 3939d3fbd75dba7e170698e30d1fcb74c6b52352

**Comment by adamhsparks** [comment]
Err, we based the code on a Mathematica model that IS published, no?

**Comment by adamhsparks** [comment]
Also, Coventry's thesis should be cited here as well.

**Comment by IhsanKhaliq** [comment]
> Err, we based the code on a Mathematica model that IS published, no?

Yes, we're safe

**Comment by IhsanKhaliq** [comment]
There would be no DOI for thesis

**Comment by adamhsparks** [comment]
Maybe not but it is citable and should be referenced.
