### ISSUE TITLE
Need a Zenodo archive

### ISSUE THREAD

**Issue by adamhsparks** [IhsanKhaliq/ascotraceR#127]
This repository should be linked with Zenodo so our first release has a DOI.

- [x] Link with Zenodo
- [ ] Create a new release
- [x] Get the DOI and add the badge to README
- [x] Add the overarching DOI to DESCRIPTION in DOI field

**Comment by IhsanKhaliq** [comment]
Closed 3b2a68c58d729662903e51030d45536e88009125, e006040f80c8082fc667b9f95700aadba95f0bc1

**Comment by adamhsparks** [comment]
There shouldn’t be a new release yet. That comes after it’s accepted on CRAN.

**Comment by IhsanKhaliq** [comment]
Closed via 2cb8200
