### ISSUE TITLE
Check vignette and update with stubble inoculum functionality

### ISSUE THREAD

**Issue by PaulMelloy** [IhsanKhaliq/ascotraceR#130]
Now that the start of the epidemic can be customised with either infected plants or stubble inoculum (or both), the vignette needs to be updated to detail this. Some defaults have changed so the results might have changed a little as well, so the vignette results need checking so that it runs as expected.

The vignette should also detail that to disable (for example) `primary_infections`, so only `stubble_inoculum` can be modelled, `primary_infection_intensity` should be set to `0`. The same can be done if only `primary_infection_foci` wants to be modelled, set to the `stubble_inoculum_intensity` to `0`

I am busy today with a kindy break-up party and my daughters birthday parties so if @IhsanKhaliq could check this, that would be super.

**Comment by IhsanKhaliq** [comment]
I made some edits and have run the valascotraceR repo too. Have you changed the values? The model is now overpredicting disease, and those stat values have gone off. See the obs vs pred proportion. For Tosari, 96% quadrats got infected by assessment 4. For Billa Billa, all quadrats got infected by assessment 6
 
![Screen Shot 2021-12-12 at 11 41 27 am](https://user-images.githubusercontent.com/54728693/145697340-a6804996-4423-4bc3-ad2e-1d9740fd08c6.png)

**Comment by IhsanKhaliq** [comment]
Billa heatmap doesnt reflect spatial spread, as all quadrats should infections
![Billa PNG](https://user-images.githubusercontent.com/54728693/145697380-1b06f1cc-cafa-43ee-8b03-4b6a50f65918.png)

**Comment by IhsanKhaliq** [comment]
Same for Tosari, 96% quadrats should show infection
![000003](https://user-images.githubusercontent.com/54728693/145697394-bf396625-d123-4679-80b6-af785f9301b5.png)

**Comment by IhsanKhaliq** [comment]
Getting this warning in valascotraceR for Billa Billa
![Screen Shot 2021-12-12 at 11 09 48 am](https://user-images.githubusercontent.com/54728693/145697409-c111f9a1-6741-488a-b819-8956fbfebe99.png)

**Comment by IhsanKhaliq** [comment]
Overall, overprediction
![spread](https://user-images.githubusercontent.com/54728693/145697418-42e6b6bb-3a8a-49a6-9aa2-f8cd18cf6779.png)

**Comment by PaulMelloy** [comment]
Changes in the model reverted, this issue is no longer relevant.
