### ISSUE TITLE
contradiction in definition of primary infection intensity

### ISSUE THREAD

**Issue by IhsanKhaliq** [IhsanKhaliq/ascotraceR#132]
And you're contradicting yourself here by talking about the amount of primary inoculum on chickpea plants, but have included infected seed too. How can a seed have `200` value when there can be only one growing point per seed?
https://github.com/IhsanKhaliq/ascotraceR/blob/543ab650bf202783cdc6c0223f2eb45984bb438d/R/trace_asco.R#L36-L39

**Comment by PaulMelloy** [comment]
It is the number of growing points per square meter, 40 seeds = 40 growing points.
These descriptions were not changed very much, from what they were before....

**Comment by IhsanKhaliq** [comment]
It doesn't matter. Your definition says, "the amount of primary inoculum as lesions on **chickpea plants** at the time of `initial_infection`".
Seed is not plant, and you will have to sow 10 quadrats exclusively with infected seed to make up to `200` growing points.

**Comment by IhsanKhaliq** [comment]
Ok this is again name confusion. `IO` should solve the problem

**Comment by IhsanKhaliq** [comment]
The definition said, primary inoculum, not primary infection. I have changed the definition as per a3754c6ac843a12e7cd88536f285975103f98658
