### ISSUE TITLE
Why not call it `seedling_inoculum_intensity` ?

### ISSUE THREAD

**Issue by IhsanKhaliq** [IhsanKhaliq/ascotraceR#133]
Primary infection can only occur on chickpea we have grown. Since you're calling primry inoculum from stubble as `stubble_inoculum_intensity`, I suggest changing seedling inoculum name from `primary_infection_intensity` to  `seedling_inoculum_intensity`. This will remove confusions

https://github.com/IhsanKhaliq/ascotraceR/blob/d3443d92f19d8128564d72324ddc08c8947d42d5/R/trace_asco.R#L140

**Comment by adamhsparks** [comment]
Why not just call it `I0` as I’ve suggested before? From _epicrop_, “I0 initial number of infective sites (integer).”

**Comment by IhsanKhaliq** [comment]
Whatever works, but the current definition is no good as primary infection occurs only on chickpea seedlings we've grown.

**Comment by adamhsparks** [comment]
I agree, it's confusing, which is why I'm making suggestions. Trying to help because I'm confused by it as well. :)

**Comment by IhsanKhaliq** [comment]
There should be similar pattern in giving names to avoid confusion #133. Either the epicrop pattern or the or the one you're already using. Whatever you like
`stubble_inoculum_intensity` to represent stubble inoculum
`seedling_inoculum_intensity` to represent seedling inoculum
`seed_inoculum_intensity` to represent seed inoculum. But each has only one growing point, so I am not sure how can the value be greater than 1

**Comment by PaulMelloy** [comment]
`IO` works. It should not be called seedling_intensity because that is not the only thing this parameter could be used to describe.

As Adam says this parameter is "initial number of infective sites (integer)" on chickpea plants in the specified square meter/s.

**Comment by IhsanKhaliq** [comment]
Ok. I thought it reffered to the infected seedlings introduced at the centre from which disease starts. `IO` should solve the problem

**Comment by IhsanKhaliq** [comment]
Changes related to the introduction of stubble inoculum intensity have been reverted, and the parameter doesn't exist. This issue is no longer relevant.
