### ISSUE TITLE
How come there are two sources of inoculum in  a single function?

### ISSUE THREAD

**Issue by IhsanKhaliq** [IhsanKhaliq/ascotraceR#134]
Both stubble and seedling have been used as the sources of primary infection?  Or it's not being used? This is why I suggested changing names to `seedling inoculum intensity`

https://github.com/IhsanKhaliq/ascotraceR/blob/d3443d92f19d8128564d72324ddc08c8947d42d5/R/trace_asco.R#L162-L165

**Comment by PaulMelloy** [comment]
I am confused, I thought I was changing this to what you requested. Parameters to describe stubble sources of inoculum and parameters to describe and plant infectious sites.

Perhaps it is best to revert this update and proceed with the previous model and simplify the `trace_asco` example so there are no warnings. #117 

I don't have time to go round in circles with this.

**Comment by IhsanKhaliq** [comment]
I think the definition was a bit confusing . The definition said, the amount of primary inoculum (referring to inoculum sources too, not primary infection.
I have changed the definition as per a3754c6ac843a12e7cd88536f285975103f98658 as defined by ARt, @PaulMelloy could you please confirm this is what you meant to write?

**Comment by PaulMelloy** [comment]
I don't understand this updated description in a3754c6ac843a12e7cd88536f285975103f98658. Why are you referring to methods in 'the experiment'. Do you mean to say 'model simulation'.

`primary_infection_intensity` or `IO` are the number of *estimated* infectious lesions/growing points on chickpea plants in a spatial unit (1x1m) at the `initial_infection` point in time. 

These (*estimated* infectious lesions/growing points on chickpea plants in a spatial unit (1x1m) at the `initial_infection` point in time) could have been infected by inoculum from any number of sources for which the *user* might postulate. However infection happened before the field observation (or imaginary field observation that the *user* might want to propose) at `initial_infection` as we are describing infectious points from that point in time.

The crop grows from seed; 
-  if we never observe disease on the plants at `initial_infection` point in time; 
-  at the location in the field `primary_infection_foci` 
-  with a disease severity that equates to `primary_infection_intensity`. 

Then the model presumes there is no disease, because we never told it **when, where** and **how much** disease there was

**Comment by IhsanKhaliq** [comment]
No by experiment I meant field experiment. This is what Art did. He observed disease in the experiment at the time of initial infection and put that in the model. This is done to compare observation with prediction (along with the same starting date, end date etc.)

![140834672-da9f49ae-c3df-44c9-9ce7-53035a4f80a5](https://user-images.githubusercontent.com/54728693/145737455-cb2cabf6-9c48-44d7-8b57-2e773ababff4.png)

**Comment by IhsanKhaliq** [comment]
"_For a comparison with the experimental results, the model was initialized with the same start and end dates (20 May and 10 November), field size (45 × 8 m), and plant density (40 plants per m2) as the experiment. The model was run with the recorded weather data. On the date of initial infection in the experiment, one infective growing point was added to each of the two subunits corresponding to the points of initial infection in the field. The model was run four times, with no wrapping option, for each cultivar so that the mean of the model runs would be comparable in both magnitude and variability with the experimental data_"

**Comment by adamhsparks** [comment]
I think you're conflating the validation exercise with just the model structure and parameters here.

There is no "experiment" in the package and it shouldn't be referred to in the parameter documentation here. It's a model that can be run to simulate your experiment. It is not strictly made for that experiment but can simulate it or others...

**Comment by IhsanKhaliq** [comment]
So how are we suppose to incorporate this if there is no parameter _"On the date of initial infection in the experiment, one infective growing point was added to each of the two subunits corresponding to the points of initial infection in the field"_

**Comment by PaulMelloy** [comment]
"On the date of `initial_infection` in the experiment, one `primary_infection_intesity` was added to each of the (two) `primary_infection_foci` corresponding to the points of initial infection in the field"

**Comment by IhsanKhaliq** [comment]
> "On the date of `initial_infection` in the experiment, one `primary_infection_intesity` was added to each of the (two) `primary_infection_foci` corresponding to the points of initial infection in the field"

AWESOME

**Comment by IhsanKhaliq** [comment]
What about the other quadrats? About `16` quadrats were infected at once at Tosari

**Comment by PaulMelloy** [comment]
https://github.com/IhsanKhaliq/ascotraceR/blob/88262dc18930fb2e2b2afffd0e8bc03f0831c6ac/R/trace_asco.R#L28-L36
Note the 

> or a `data.frame` with column names \sQuote{x}, \sQuote{y} and \sQuote{load}. The `data.frame` inputs inform the model of the specific grid cell/s coordinates where stubble is located in the paddock. The \sQuote{load} column is optional and can specify the `stubble_inoculum_intensity` for each coordinate. If \sQuote{load} is not specified `stubble_inoculum_intensity` is substituted for all coordinates.

https://github.com/IhsanKhaliq/ascotraceR/blob/88262dc18930fb2e2b2afffd0e8bc03f0831c6ac/tests/testthat/test-trace_asco.R#L165-L183

**Comment by IhsanKhaliq** [comment]
Just a thought......
We are good for Billa Billa, but Tosari had about 16 quadrats infected at the time of initial infection. So we can put 1 for Billa Billa and 16 for Tosari? Future models should actually put the spatial locations of those quadrats. As long as we don't call it simulated growing infectious growing, we are good. I mean we can call it that too if we are not comparing with the observation, but here we should put what we saw in the paddock

**Comment by PaulMelloy** [comment]
You could easily put 16 for Tosari, just feed the parameter `primary_infection_foci` a data.frame of the coordinates and infection intensity. No changes are needed to the model to do that.

**Comment by IhsanKhaliq** [comment]
I thought we could simply do this in valascotraceR?
primary_infection_intesity = 16 for Billa Billa
primary_infection_intesity = 1 for Tosari

**Comment by PaulMelloy** [comment]
Your data.frame might look something like this
| x | y | load |
|---|---|---|
| 5 | 1 | 5|
| 5 | 5 | 13|
| 5 | 10 | 20|
| 5 | 15 | 40|
| 5 | 20 | 20|
| 1 | 5 | 10|
| 1 | 10 | 20|

ect...

**Comment by PaulMelloy** [comment]
> I thought we could simply do this in valascotraceR? primary_infection_intesity = 16 for Billa Billa primary_infection_intesity = 1 for Tosari

Are you saying `intensity` (quantity of inoculum in one spatial unit
or
16 `foci` (different inoculuated spatial units)

**Comment by IhsanKhaliq** [comment]
Intensity
Foci is just central quadrat in our case (primary infection foci.......a place where inoculum is placed at the beginning of the experiment to initiate disease spread). It is the F quadrat

![Capture1111](https://user-images.githubusercontent.com/54728693/145743852-44dff991-7517-4a0e-9142-bc2502ff5a76.PNG)

**Comment by IhsanKhaliq** [comment]
> `ity` (quantity of inoculum in one spatial unit

16 quadrats with infection

**Comment by IhsanKhaliq** [comment]
![water](https://user-images.githubusercontent.com/54728693/145744197-a4b47b11-1518-41d5-a1f3-0f516ca4393f.PNG)

**Comment by PaulMelloy** [comment]
You have lost me

**Comment by IhsanKhaliq** [comment]
> I don't follow what you are trying to say

Primary infection foci is the just the inoculated central quadrat (F quadrat)

**Comment by PaulMelloy** [comment]
> What about the other quadrats? About `16` quadrats were infected at once at Tosari

What do you mean by this then? Were 16 quadrats infected at `initial_infection`?

**Comment by IhsanKhaliq** [comment]
Disease was observed in one quadrat at Billa Billa and 16 quadrants at Tosari. I need to double check the Tosari numbers in an hour. On the way to the gym. I need to get big

Sent from iPhone


________________________________

**Comment by IhsanKhaliq** [comment]
@PaulMelloy we can go with your statement _"On the date of initial_infection in the experiment, one primary_infection_intesity was added to each of the (two) primary_infection_foci corresponding to the points of initial infection in the field"_

I checked the excel sheet. Infection was observed in one inoculated central quadrat (primary infection foci) at _**Billa Billa**_ during assessment 2 (date when infection was first observed)

![Billa](https://user-images.githubusercontent.com/54728693/145901049-6bb115b3-722b-4322-b84c-501e73990b09.png)

 Infection was observed in three inoculated central quadrat (primary infection foci) at _**Tosari**_ during assessment 1 (date when infection was first observed). 16 plants were infected first, not quadrats

![Screen Shot 2021-12-14 at 8 42 01 am](https://user-images.githubusercontent.com/54728693/145901247-76fc2c8f-cc1a-4054-bd02-6117b3ba06c5.png)

So the value of primary infection intensity is 3 (3 quadrats) for Tosari and 1 for Billla Billa. I think we're in a good shape now to wrap up things because this has exceptionally long

**Comment by IhsanKhaliq** [comment]
> > What about the other quadrats? About `16` quadrats were infected at once at Tosari
> 
> What do you mean by this then? Were 16 quadrats infected at `initial_infection`?

3 quadrats (16 plants, I just double checked) for Tosari and 1 quadrat for Billa Billa at `initial_infection`

**Comment by PaulMelloy** [comment]
This discussion seems more applicable to the valascotraceR.
We should only be focused on preparing the package for release on cran

**Comment by IhsanKhaliq** [comment]
@PaulMelloy `primary_infection_intensity` = 3    for Tosari
`primary_infection_intensity` = 1   for Billa Billa

Is that how we're putting the value of the number of infected quadrats observed at the time of `initial_infection` in field experiment into the model? If so, we can close this issue

**Comment by IhsanKhaliq** [comment]
We are using only one inoculum source. And I am going to open another issue for `primary_infection_intensity` in the valascotraceR repository
