### ISSUE TITLE
Why is it relevant for random foci only?

### ISSUE THREAD

**Issue by IhsanKhaliq** [IhsanKhaliq/ascotraceR#135]
A central foci can have a value of `1` . One is a number too, although small 

https://github.com/IhsanKhaliq/ascotraceR/blob/d3443d92f19d8128564d72324ddc08c8947d42d5/R/trace_asco.R#L40-L41

**Comment by adamhsparks** [comment]
I can't see how you would have two central foci. It's either a central focus (1 in the middle) or it's not a central focus so you'd be using random foci.

**Comment by IhsanKhaliq** [comment]
You could have one random foci too

**Comment by IhsanKhaliq** [comment]
Closed 153564b54a18be2606a09d6452b0bce49117f7b7

**Comment by adamhsparks** [comment]
Yes, you can set it to 1. The documentation doesn't say you can't?
