### ISSUE TITLE
Why is primary infection intensity zero and 1 at the same time?

### ISSUE THREAD

**Issue by IhsanKhaliq** [IhsanKhaliq/ascotraceR#137]
I am trying to figure out what has changed that the model is over-predicting disease

https://github.com/IhsanKhaliq/ascotraceR/blob/76c5b20fdebc8bc8587b8f16cfab98729d63f3a6/R/trace_asco.R#L146-L169

**Comment by IhsanKhaliq** [comment]
Is this check working if the model is the value of primary infection intensity is zero and is still simulating spread

 https://github.com/IhsanKhaliq/ascotraceR/blob/76c5b20fdebc8bc8587b8f16cfab98729d63f3a6/R/trace_asco.R#L192-L199

**Comment by PaulMelloy** [comment]
> I am trying to figure out what has changed that the model is over-predicting disease
> 
> https://github.com/IhsanKhaliq/ascotraceR/blob/76c5b20fdebc8bc8587b8f16cfab98729d63f3a6/R/trace_asco.R#L146-L169

The former is the example given to users and found in the R help file. It should be a "toy" example of how to run the model, and some basic features.

the latter is the function defaults, that is if the user does not enter a value to the corresponding argument the default value is used.

I would advise you specify values for both `primary_infection_intensity` and `stubble_inoculum_intensity `. And in fact now I think about it, perhaps both arguments should probably have defaults of `0`. That way the user has to always specify the amount of starting inoculum or get no disease.

**Comment by IhsanKhaliq** [comment]
Closed fba7f3a
