### ISSUE TITLE
devtools::buildreadme reverts changes 

### ISSUE THREAD

**Issue by PaulMelloy** [IhsanKhaliq/ascotraceR#143]
When I run `devtools::build_readme()` it reverts any changes that were made to the `readme.md`

Not sure why this is happening

**Comment by PaulMelloy** [comment]
related to some comments made in #140

**Comment by PaulMelloy** [comment]
This should be fixed in 486209c19d0672b8e248ac3a25360aec65f8a06a

Can you check that the readme.Rmd reads correctly @IhsanKhaliq so the readme.md is rendered correctly from it

**Comment by IhsanKhaliq** [comment]
@PaulMelloy what I need to do here? It looks fine to me. Before CRAN submission, please check the issue on `valascotraceR`. One parameter has disappeared

**Comment by IhsanKhaliq** [comment]
It keeps on reverting for me too. Is it because of two readme files? I deleted one but then I am getting an error. Currently, these   are missing. I add them but they keep on reverting

**Comment by adamhsparks** [comment]
For one thing, the README.Rmd doesn't knit properly at all when I try to knit it in RStudio. It errors on Line 93 with a message about an unused argument, `primary_incoulum_intensity = 100`.

**Comment by adamhsparks** [comment]
whoops, I had an old version installed on my personal laptop

**Comment by adamhsparks** [comment]
Seems to work fine for me? I just pushed changes after trying `devtools::build_readme()`

**Comment by IhsanKhaliq** [comment]
This seems to be working as Adam mentioned above

**Comment by PaulMelloy** [comment]
@IhsanKhaliq I noticed the last couple of commits you have changed the *regular* markdown file `README.md` .
Please check and change the The **R** markdown file `README.Rmd`.
The `README.Rmd` writes over the `README.md` file when the readme is built with `devtools::build_readme()`

Also make sure you are on the `master` branch as this is the most recent stable version.

**Comment by PaulMelloy** [comment]
When I run `devtools::build_readme()` it still makes changes to `README.md`.
Can you please check again @IhsanKhaliq

**Comment by IhsanKhaliq** [comment]
I just created pull request as Adam made changes to dev. You can merge that pull request

**Comment by IhsanKhaliq** [comment]
There are no conflicts

**Comment by IhsanKhaliq** [comment]
It works on `main` as per 6bd6fd2

**Comment by adamhsparks** [comment]
If you don't want the values to change, you need to use `set.Seed()`.

**Comment by IhsanKhaliq** [comment]
Ahhh that's happening because seed number hasn't been set. That's fine then. I think this issue can be closed
