### ISSUE TITLE
Rename master branch to main

### ISSUE THREAD

**Issue by PaulMelloy** [IhsanKhaliq/ascotraceR#145]
@IhsanKhaliq I think you are the only one who can do this as the owner of the repository
can you rename the branch to `main`

See
https://github.com/github/renaming

**Comment by IhsanKhaliq** [comment]
I have renamed the branch but can't seem to delete the `master` branch. It's recommended to delete the `master` branch https://stackoverflow.com/questions/6591213/how-do-i-rename-a-local-git-branch. The issue can be closed if only renaming is required
![Screen Shot 2021-12-19 at 7 25 53 pm](https://user-images.githubusercontent.com/54728693/146670180-bfaf8c52-b1e1-4d90-b850-6e7ab4308d88.png)

**Comment by PaulMelloy** [comment]
I posted a link to how to do it in github.
The link you shared is not how to rename the github repository name, but renaming a repo locally. Please follow the instructions I posted above.

> See
> https://github.com/github/renaming

**Comment by IhsanKhaliq** [comment]
I have already renamed the branch, but wanted to delete `master` branch on github. I could delete it locally using `git branch -d master`. The internet suggest that remote master branch can't be deleted

**Comment by IhsanKhaliq** [comment]
The link you posted rename branch on `remote` only, and not in local environment

**Comment by IhsanKhaliq** [comment]
Do you know how to delete `master` on `remote`?

**Comment by IhsanKhaliq** [comment]
Closed https://stackoverflow.com/questions/12208751/i-cant-delete-a-remote-master-branch-on-git

**Comment by PaulMelloy** [comment]
Thanks 
The remote branch is the one which needed renaming
