### ISSUE TITLE
Readme file doesn't knit

### ISSUE THREAD

**Issue by IhsanKhaliq** [IhsanKhaliq/ascotraceR#148]
![Screen Shot 2021-12-21 at 9 00 35 am](https://user-images.githubusercontent.com/54728693/146843968-f17d1c89-530e-496d-80aa-39330562a5e4.png)

**Comment by IhsanKhaliq** [comment]
The file can only be knitted when typed `install.packages("ascotraceR", repos="http://cran.us.r-project.org")`

**Comment by IhsanKhaliq** [comment]
That doesn't work. Are you able to knit on your machine? We just want this to appear install.packages("ascotraceR") instead of install.packages("ascotraceR", repos="http://cran.us.r-project.org"). It's only happening for this package

**Comment by adamhsparks** [comment]
This depends on how long it's been on CRAN and if it's propagated through all the mirrors to the one you're system defaults to.

**Comment by adamhsparks** [comment]
The issue I see here is that the code to install it runs and it shouldn't be run every time you knit the Rmd.

**Comment by IhsanKhaliq** [comment]
The internet suggests something related to setting mirror. I have currently used this solution for now https://stackoverflow.com/questions/33969024/install-packages-fails-in-knitr-document-trying-to-use-cran-without-setting-a

But we need to somehow get rid of `repos="http://cran.us.r-project.org"` when installing packages

**Comment by adamhsparks** [comment]
Yes, just delete that portion from the README and don't execute that code as I said, that's the issue here. You shouldn't be installing it every time you knit.

**Comment by IhsanKhaliq** [comment]
Then I can't push the changes to appear in readme. Tried that

**Comment by adamhsparks** [comment]
What? I'm describing the workflow I use for every one of my packages.

**Comment by IhsanKhaliq** [comment]
When I delete `repos="http://cran.us.r-project.org"` from `install.packages()` the package won't knit hence I can't push the changes. I just want `install.packages("ascotraceR")` not `install.packages("ascotraceR", repos="http://cran.us.r-project.org")` to appear in `readme`

**Comment by adamhsparks** [comment]
Yes, as I keep saying, "DON'T INSTALL THE PACKAGE EVERY TIME YOU KNIT, **DO NOT EXECUTE THAT CODE CHUNK**".

Just use `install.packages("ascotraceR")` in that chunk. End of story.

**Comment by IhsanKhaliq** [comment]
When I only use `install.packages("ascotraceR")`, I get the following run, so can't knit/push
![Screen Shot 2021-12-21 at 9 54 08 am](https://user-images.githubusercontent.com/54728693/146848050-276d44d1-5425-406f-aad0-5da8ec89172f.png)

**Comment by IhsanKhaliq** [comment]
But when I use this `install.packages("ascotraceR", repos="http://cran.us.r-project.org")` everything works. It could be just my computer I don't know

**Comment by adamhsparks** [comment]
For the last time.

You do NOT install the package from CRAN EVERY time you KNIT the README. That's it. 

I've fixed it in `dev`.
