### ISSUE TITLE
`dev` version is out of date

### ISSUE THREAD

**Issue by adamhsparks** [IhsanKhaliq/ascotraceR#149]
I was trying to reproduce Ihsan's "issue" knitting the README however the README in `dev` is out of date.

Changes should be made in `dev` and merged to `main` when stable or for releases. Not the other way around.

**Comment by PaulMelloy** [comment]
Hi @adamhsparks ,
Yes this was my fault, I was doing the final cran submission checks in `main`.
Merge request #150  should have corrected this issue
