### ISSUE TITLE
URL isn't clearly found

### ISSUE THREAD

**Issue by adamhsparks** [IhsanKhaliq/ascotraceR#151]
I'm assuming that the pkgdown site is being built?

We should have the URL clearly stated for the documentation site. 

All GitHub repositories allow this, it should just be updated to reflect the page's URL in the repository.
See the example from _epicrop_.

<img width="387" alt="Screen Shot 2021-12-21 at 8 07 08 am" src="https://user-images.githubusercontent.com/3195906/146848943-c7177a0c-5155-4d4f-9267-9c6bcb45b12f.png">

@IhsanKhaliq, as the repo owner, you're the only person who can do this.

**Comment by adamhsparks** [comment]
Confirming that it's there: https://ihsankhaliq.github.io/ascotraceR/

**Comment by IhsanKhaliq** [comment]
I added the URL and keywords
