### ISSUE TITLE
calc_new_gp returns a floating point double

### ISSUE THREAD

**Issue by PaulMelloy** [IhsanKhaliq/ascotraceR#60]
The `calc_new_gp` function needs to be checked in Mathematica code and literature that it is supposed to return a floating-point number.
I think it would make more sense if it returned an integer.

I am considering wrapping the output in the `random_integer_from_real()` function

**Comment by IhsanKhaliq** [comment]
If there is no further improvements on this then this issue can be closed too

**Comment by adamhsparks** [comment]
Sorry, this should be left open. It’s unresolved but shouldn’t affect the release of the initial version since everything works.

**Comment by PaulMelloy** [comment]
Complete
