### ISSUE TITLE
`primary_infection_intensity` function is misleading

### ISSUE THREAD

**Issue by IhsanKhaliq** [IhsanKhaliq/ascotraceR#71]
This is the description of the function `The intensity of the starting epidemic as
described by the number of number of sporulating growing points`. 
This is the function 
 if (primary_infection_intensity > seeding_rate) {
 stop(
  "primary_infection_intensity exceeds the number of starting growing points - 'seeding_rate': ",
  seeding_rate
 )
}

Reasons why it's invalid 

1. The function is saying conidia splash from primary foci (stubble), then cause primary infection. Intensity refers to how many lesions resulting from that primary spread, so lesions can be greater than seeding rate

2. If I increase or decrease the value, it doesn't have much effect on the disease spread

3. The major problem is the way the model is interpreting it. It the value is 100, then the model can produce a total of 100 lesions over the duration of the experiment

![s-gp-1000](https://user-images.githubusercontent.com/54728693/126576653-b4709d8d-4b84-42ca-a807-1d0af9b98c37.png)

It the value is 1000, then the model can produce a total of 1000 lesions over the duration of the experiment

![s-gp-1000](https://user-images.githubusercontent.com/54728693/126576676-b1794af1-3be8-425b-86dd-0c800e3e95e9.png)

3. When the function is temporarily removed, the model can produce only 4 lesions per quadrat over the duration of the experiment 
![00d2c16c-72d7-4136-9951-0ce7da5a8c75](https://user-images.githubusercontent.com/54728693/126576922-fd9b4843-0f2a-43b4-aa22-94835ae342ca.png)

**Comment by PaulMelloy** [comment]
Ok time to address this can of worms.
`primary_innoculum_intensity` is actually misleading for what the model assumes about it as an input. This is because `primary_infection_intensity` / `primary_innoculum_intensity` is linked to the number of growing points.
So be definition `primary_infection_intensity` is the inoculum that is sourced from plants in the field (not crop debris).
This is how the model has been defined. I am reluctant to change this functionality, so I am going to revert all descriptions of `primary_innoculum_intensity` to `primary_infection_intensity`.

Because this model **should** simulate from infested stubble as discussed in #117  and #104, I will then add a **new feature** describing `primary_innoculum_intensity`. However, for clarity, I will call it `stubble_innoculum_intensity`. This will also need a new parameter `stubble_inoculum_coords` where the location of any stubble can be applied, with options to define this as "centre" or "random" similar to how `primary_infection_foci` can be defined.

Stubble inoculum presumably behaves differently to plant inoculum and I will assume it decays over time, so I will also introduce another **new parameter** `stubble_innoculum_decay` which defines the rate at which the inoculum decays over time (note: this should probably be based on decay against time and rainfall, but that can be a future feature).

This will also make this model more distinct from Arts model which only assumes inoculum occurs from plant-based inoculum.

**Comment by IhsanKhaliq** [comment]
Feel free to change others, but please don't do this. This is a pathological sin and will lead to straight rejection. Everything decays over time, not just stubble 

Stubble inoculum presumably behaves differently to plant inoculum and I will assume it decays over time, so I will also introduce another new parameter stubble_innoculum_decay which defines the rate at which the inoculum decays over time (note: this should probably be based on decay against time and rainfall, but that can be a future feature).

**Comment by IhsanKhaliq** [comment]
> Ok time to address this can of worms. `primary_innoculum_intensity` is actually misleading for what the model assumes about it as an input. This is because `primary_infection_intensity` / `primary_innoculum_intensity` is linked to the number of growing points. So be definition `primary_infection_intensity` is the inoculum that is sourced from plants in the field (not crop debris). This is how the model has been defined. I am reluctant to change this functionality, so I am going to revert all descriptions of `primary_innoculum_intensity` to `primary_infection_intensity`.
> 
> Because this model **should** simulate from infested stubble as discussed in #117 and #104, I will then add a **new feature** describing `primary_innoculum_intensity`. However, for clarity, I will call it `stubble_innoculum_intensity`. This will also need a new parameter `stubble_inoculum_coords` where the location of any stubble can be applied, with options to define this as "centre" or "random" similar to how `primary_infection_foci` can be defined.
> 
> Stubble inoculum presumably behaves differently to plant inoculum and I will assume it decays over time, so I will also introduce another **new parameter** `stubble_innoculum_decay` which defines the rate at which the inoculum decays over time (note: this should probably be based on decay against time and rainfall, but that can be a future feature).
> 
> This will also make this model more distinct from Arts model which only assumes inoculum occurs from plant-based inoculum.

Both are stubble and seedlings are the sources of infection, and are exactly the same. Primary Infection can only occur on the seedling we have grown in the field. But feel free to change the names if that makes you happy

**Comment by adamhsparks** [comment]
The name clearly is confusing and I don’t see an issue with what Paul proposed about stubble inoculum. We have other models that provide decay functions for sporulation. So there are no “sins” here.

However, this is rather simple, IMO. The name needs to change and be clearly defined. `I0` or `initial_infective_sites` either one seems to be what we’re defining here. As I understand it, this is just the number of infectious sites capable of causing disease at other growing points at the time defined by the user when the model run starts. We’re getting too hung up on the source. It doesn’t matter for the model the way it’s written. You could refine it further by adding the stubble functionality but that’s going to take more research and time to do properly.

**Comment by PaulMelloy** [comment]
> Both are stubble and seedlings are the sources of infection, and are exactly the same. Primary Infection can only occur on the seedling we have grown in the field. But feel free to change the names if that makes you happy

Agreed. There will be no changes to how plants become infected, only how we are defining the source of inoculum (`stubble_innoculum_intensity`) and/or observation of infected growing points early in an epidemic (where infection may have been from seed, in cases where fungicide coating was not used)

**Comment by IhsanKhaliq** [comment]
> The name clearly is confusing and I don’t see an issue with what Paul proposed about stubble inoculum. We have other models that provide decay functions for sporulation. So there are no “sins” here.
> 
> However, this is rather simple, IMO. The name needs to change and be clearly defined. `I0` or `initial_infective_sites` either one seems to be what we’re defining here. As I understand it, this is just the number of infectious sites capable of causing disease at other growing points at the time defined by the user when the model run starts. We’re getting too hung up on the source. It doesn’t matter for the model the way it’s written. You could refine it further by adding the stubble functionality but that’s going to take more research and time to do properly.

HOW WOULD YOU INTRODUCE SPORE DECAY IN THIS MODEL, IF IT'S NOT A SIN? I'M CONFUSED BUT HAPPY TO BE GUIDED BY YOUR WISDOM

**Comment by adamhsparks** [comment]
@IhsanKhaliq, I stated it was possible but it would take more time and research. Not that we should do it for this model. There are other models that implement these sorts of factors but this one does not need it. 

Since it’s Saturday and I’m having ☕️, my wisdom for the day is take some time off and enjoy your weekend.

**Comment by IhsanKhaliq** [comment]
> @IhsanKhaliq, I stated it was possible but it would take more time and research. Not that we should do it for this model. There are other models that implement these sorts of factors but this one does not need it.
> 
> Since it’s Saturday and I’m having ☕️, my wisdom for the day is take some time off and enjoy your weekend.

What you're referring to is possible when you do disease forecasting for the next season. That is, when you put infested stubble out there and quantify spore dispersal at different times. Initially, more spore would disperse and decline towards the end of growing season because of the depletion of inoculum source. This is mainly done to identify possible sowing dates, as already done by DPIRD for some pathosystems. Here we're tying to determine the spatial and temporal spread patterns within season, so it's not applicable, as disease would increased with time due to increase in the number of infected seedlings, not decrease. I'm just that if the reviewer saw that seedling and inoculum have been treated differently and  saw `stubble_inoculum_decay`, he would reject the paper straight away

**Comment by adamhsparks** [comment]
No. You clearly don’t know what I’m referring to or thinking of here. We do have models that predict decay in-season it is possible, but it is out of scope for this model as it sits right now. 

Cheers!

**Comment by PaulMelloy** [comment]
Was busy cleaning the house so did not get to this till now.

The decay parameter is optional to use. So don't be too concerned. 
My thoughts were that the default value `1` would indicate no stubble inoculum decay, `0.6` = 40% decay, `0.2` = 80% decay, ect..
Or perhaps I will invert that scale if it is easier to understand...

You don't have to use it but perhaps some people may want to define some sort of stubble decay as is common in other models.

**Comment by IhsanKhaliq** [comment]
> Was busy cleaning the house so did not get to this till now.
> 
> The decay parameter is optional to use. So don't be too concerned. My thoughts were that the default value `1` would indicate no stubble inoculum decay, `0.6` = 40% decay, `0.2` = 80% decay, ect.. Or perhaps I will invert that scale if it is easier to understand...
> 
> You don't have to use it but perhaps some people may want to define some sort of stubble decay as is common in other models.

HOW DO YOU MEASURE THIS? 1 would indicate no stubble inoculum decay, 0.6 = 40% decay, 0.2 = 80% decay

**Comment by PaulMelloy** [comment]
Available inoculum is measured in wind tunnels and/or microscopically by inspecting pycnidia / perithecia.
This is what we were doing with the Yellow spot trials "weathering stubble", albeit this was with ascospores, not conidia.

The decay scale is a proportion, so you could postulate that each rainfall event 5% of the inoculum decays (or does not replenish conidia). Therefore you would use a value of `0.95` and multiply that by the `stubble_inoculum_intensity`, or `stubble_lesions`

**Comment by PaulMelloy** [comment]
I believe this issue has now been addressed with the addition of stubble inoculum variables created in #129 
Ihsan can you check that you are happy with how the extra variables have been named and close this issue when you are done.

**Comment by IhsanKhaliq** [comment]
It's not applicable for this model. Since the value is 1, I am not bothered by it and closing the issue
https://github.com/IhsanKhaliq/ascotraceR/blob/e6092a4a6a3dc202c7de0f280ef688f110341258/R/trace_asco.R#L59-L63
